const data = [
    { id: 1, name: 'Idly' },
    { id: 2, name: 'Dosa' },
    { id: 3, name: 'Puri' },
    { id: 4, name: 'Tea' },
    { id: 5, name: 'Coffee' },
    { id: 6, name: 'Lemon tea' },
    { id: 7, name: 'Chole bhature' },
    { id: 8, name: 'Veg fried rice' },
    { id: 9, name: 'Biryani' },
    { id: 10, name: 'Gulab Jamun' },
    { id: 11, name: 'Double-ka-Meetha' },
    { id: 12, name: 'Kaal Jamun' },
    { id: 13, name: 'Samosa' },
    { id: 14, name: 'Punugulu' },
    { id: 15, name: 'Onion pakodi' },
    { id: 16, name: 'Veg noodles' },
    { id: 17, name: 'Veg fried ricee' },
    { id: 18, name: 'Veg manchuria' },
    { id: 19, name: 'Chicken noodles' },
    { id: 20, name: 'Chicken fried rice' },
    { id: 21, name: 'Chicken manchuria' },
    { id: 22, name: 'Egg fried rice' },
    { id: 23, name: 'Chicken 65' },
    { id: 24, name: 'Egg puff' },
    { id: 25, name: 'Chicken puff' },
    { id: 26, name: 'veg puff' },
    { id: 27, name: 'Veg maggi' },
    { id: 28, name: 'Veg sandwich' },
    { id: 29, name: 'Chicken sandwich' },
    { id: 30, name: 'Black forest' },
    { id: 31, name: 'cup cake' },
    { id: 33, name: 'Chaco pastery' },
]
  export default data